### ISSUE TITLE
Python 3.5 results are not same to Python 2.7

### ISSUE THREAD

**Issue by NeoBoy** [pyannote/pyannote-metrics#10]
![image](https://cloud.githubusercontent.com/assets/4787117/24361806/5d61085a-1324-11e7-83ac-f62061bf8d96.png)
I ran the example notebook and results for Cluster purity and coverage are not same, a warning 
(utils.py:160: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  "'uem' was approximated by the union of 'reference' ") is generated

**Comment by hbredin** [comment]
A screenshot is not very helpful. Can you please provide me with a simple Python script that reproduce the error (expected output, actual output).

**Comment by NeoBoy** [comment]
Sorry for that, I am running the example file by you. I just changed the **print** statements which can't directly run in Python 3 by adding ()

**Comment by NeoBoy** [comment]
No other change in the code

**Comment by hbredin** [comment]
These notebooks have not been updated for a while.
Can you check with the latest version I just released?

Also, do you confirm you ran both Python 2.7 and Python 3.5 and did not get the same results between your two runs?

**Comment by NeoBoy** [comment]
I ran the code on python 3.5 and compared the results with the ones already in the notebook which clearly was python 2 (evident from print statement used as a keyword instead of a function). My Python 2.7 installation was giving import issue on the notebook so it didn't run

**Comment by NeoBoy** [comment]
Seen the current notebook, they are **now** same to what I am getting in Python 3.5 apart from the **userWarning**
