### ISSUE TITLE
Package gets installed in Python 2.7 but gives error when importing in code

### ISSUE THREAD

**Issue by NeoBoy** [pyannote/pyannote-metrics#11]
![image](https://cloud.githubusercontent.com/assets/4787117/24362254/adfa0de2-1325-11e7-9121-1aaec4be1afa.png)

I installed the package in Ubuntu 16.04 LTS with anaconda distribution and python 2.7 which happens without any issue. But when I use the example notebook, I get import error 
(ImportError: /home/neoboy/anaconda2/lib/python2.7/site-packages/banyan_c.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm)

**Comment by hbredin** [comment]
Sorry. Never encountered this issue before. 
Can you provide me with a very simple set of instructions to reproduce the error?

**Comment by NeoBoy** [comment]
I was just running the example notebook provide by you and error occurs after I run line 2 of the notebook 
**from pyannote.core import Annontation, Segment**

**Comment by hbredin** [comment]
Can you provide with the complete set of installation instructions you used so that I can try to reproduce them?

**Comment by NeoBoy** [comment]
I downloaded the anaconda python 2 installer for Linux, installed it and then installed **gcc** and used pip to install pyannote.metrics

**Comment by hbredin** [comment]
Here is what I did:

```bash
$ conda create -n pyannote-metrics-py27 python=2.7 anaconda
$ source activate pyannote-metrics-py27
$ conda install gcc
$ pip install pyannote.metrics
$ python -c "from pyannote.core import Segment, Annotation"
```

This does not raise any error: I cannot replicate your error.

**Comment by NeoBoy** [comment]
I have identified the problem. Mistakenly I installed the package without installing the **gcc** first and somehow package did get installed but giving the error when importing the package. I retried installation after installing **gcc** but pip was cached so error was not disappearing. After using **pip install --ignore-installed --upgrade pyannote.metrics**, the package is now functional.
