### ISSUE TITLE
Avoid divide by zero error when computing cross entropy

### ISSUE THREAD

**Issue by wq2012** [pyannote/pyannote-metrics#14]
Suggest:
In DiarizationHomogeneity.compute_components(),
change
`matrix = reference.support() * hypothesis.support()`
to
`matrix = reference.support() * hypothesis.support() + 1e-8`

**Comment by hbredin** [comment]
Could you please provide me with a simple Python script to reproduce the error you get?

**Comment by wq2012** [comment]
Sorry I forgot what was my example. But it's worth adding tests for DiarizationHomogeneity.

And in general, for entropy, p * ln( p ) should return 0 when p == 0, rather than computing ln( 0 ) and raise error.

**Comment by hbredin** [comment]
Next release will contain a fix for this bug. Thanks for reporting it!
