### ISSUE TITLE
Add option to ignore overlapping speech regions

### ISSUE THREAD

**Issue by Jamiroquai88** [pyannote/pyannote-metrics#15]
Hi, is there some way to ignore overlaping speech in DER scoring? It is quite common to use collar with size 0.25 (I know how to do that), but I can not see option to ignore overlaps. Thanks

**Comment by hbredin** [comment]
What does "ignoring overlaps" mean exactly? 

At least two different ways of doing this come to mind:
- remove overlapping speech regions completely from evaluation (by extruding the annotated region the same way it is already done for collars)
- keep evaluating those regions, but not count false alarms (which is the default behavior right now)

I don't have time right now to work on this but I'd gladly consider a pull request adding this feature.

The former is easier to implement than the latter, and could be easily added to `UEMSupportMixin `: 
https://github.com/pyannote/pyannote-metrics/blob/develop/pyannote/metrics/utils.py#L35 and all metrics supporting this `UEMSupportMixin`.

**Comment by Jamiroquai88** [comment]
ignoring overlaps means, that you do not evaluate overlapped segments, from md-eval.pl script: to limit scoring to those time regions in which only a single speaker is speaking

**Comment by hbredin** [comment]
`limit scoring to those time regions in which only a single speaker is speaking`

Does this mean that regions in which no speaker is speaking are removed as well? 
In other words, should non-speech regions be discarded as well? 
This could have a huge impact on files with a lot of non-speech regions...

**Comment by Jamiroquai88** [comment]
no, you still score regions with non-speech as a part of DER, you just do not score overlapped regions. Point is, that very common DER setup is with collar of size 0.25 and without scoring overlapped regions, because it is too difficult to detect and assign overlapped segments.

**Comment by hbredin** [comment]
OK. Got it.

Not sure "being too difficult" is a good justification for adding such a feature, though...
On the other hand, the fact that this is a very common DER setup is.

Therefore, I'll try to implement this in next release but cannot provide any ETA.

In the meantime, I would gladly guide you if you'd like to add it yourself. 
This is (more or less) just a matter of finding overlapping region (using `reference.co_iter(reference)` for instance) and then extrude those regions from `uem`.

**Comment by hbredin** [comment]
A new `skip_overlap` option has been added. It is available in the `develop` branch and will be part of next official release.

@Jamiroquai88 I would really appreciate if you could give me some feedback on this.
