### ISSUE TITLE
DER computation on bunch of files

### ISSUE THREAD

**Issue by bchinnari** [pyannote/pyannote-metrics#30]
Hi All, 
I installed the tool. I want to compute the overall diarization error rate.
I have bunch of reference files and hypothesis files in rttm format.
How do I compute DER using this tool. Kindly let me know.

Thanks
PS:I went through the documentation once. I could not figure out how.

**Comment by hbredin** [comment]
http://pyannote.github.io/pyannote-metrics/tutorial.html should give you a hint.

All that's missing from the tutorial is the part where you parse the RTTM file into the `reference` and `hypothesis` objects.

**Comment by hbredin** [comment]
Closing stalled issues. Please reopen if needed.
