### ISSUE TITLE
error in pip install on windows

### ISSUE THREAD

**Issue by chanansh** [pyannote/pyannote-metrics#6]
]
    banyan\_int_imp\_build_tree_imp.cpp(181): note: see reference to class template instantiation '_KnownMetadataBuilder<Alg_Tag,Key_Type,_NullMetadataTag,std::less<Key_Type>>' being compiled
            with
            [
                Alg_Tag=_RBTreeTag,
                Key_Type=UnicodeString
            ]
    banyan\_int_imp/_set_tree_imp.hpp(124): error C3861: 'back_inserter': identifier not found
    banyan\_int_imp/_set_tree_imp.hpp(131): error C3861: 'back_inserter': identifier not found
    banyan\_int_imp/_set_tree_imp.hpp(138): error C3861: 'back_inserter': identifier not found
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by hbredin** [comment]
Unfortunately I never tried installing `pyannote.metrics` on Windows, nor have a Windows machine to test it. May I suggest you try installing in a `conda` environment?

```bash
conda create -n pyannote-metrics-py35 python=3.5 anaconda
source activate pyannote-metrics-py35
conda install gcc
pip install pyannote-metrics
```

**Comment by chanansh** [comment]
fix: add #include <iterator> to _build_tree_imp.cpp
see https://github.com/cpcloud/banyan/issues/3
based on: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-reviews/e3qaU4ph73g

**Comment by hbredin** [comment]
I'd be happy to merge a pull request in https://github.com/pyannote/pyannote-banyan

**Comment by hbredin** [comment]
Latest release of https://github.com/pyannote/pyannote-core (v1.0) solves this problem: `banyan` is no longer a dependency.
