### ISSUE TITLE
errors + correct do not sum to 100% - is this by design?

### ISSUE THREAD

**Issue by chananshgong** [pyannote/pyannote-metrics#7]
According to the DER tutorial here: http://www.xavieranguera.com/phdthesis/node108.html
The FA + MD + CONFUSION should all add up to the DER.

However, in the example [here](http://nbviewer.jupyter.org/github/pyannote/pyannote-metrics/blob/master/doc/pyannote.metrics.diarization.ipynb): 
{u'confusion': 7.0,
 u'correct': 22.0,
 u'diarization error rate': 0.5161290322580645,
 u'false alarm': 7.0,
 u'missed detection': 2.0,
 u'total': 31.0}
The DER is  0.5161290322580645 , and multiplying by total 31, one get 16, which indeed is the sum of confusion + false alarm + missed detection. However, adding correct (21) to errors (16) is 37 which is more than 100% (total =31)

**Comment by hbredin** [comment]
Yes. This is by design. 

Also note that `DER` may be greater than 1 in some cases. 
This is due to the fact that the denominator (`total`) is the total duration of speech in the reference, not the total duration of the file.

**Comment by chanansh** [comment]
But why don't correct + FA + MD + confused = total?is total the reference while the sum above is of the hypothesis total?

**Comment by hbredin** [comment]
OK. Let's summarize:

 - false alarm = reference non-speech regions tagged as speech in hypothesis
 - missed detection = reference speech regions tagged as non-speech in hypothesis
 - confusion = reference and hypothesis agree that this is a speech region, but hypothesis is wrong on the identity of the speaker
 - correct = reference and hypothesis agree that this is a speech region and hypothesis is right about the identity of the speaker

Overall, you can sum those values as follows:

 - correct + false alarm + confusion = total speech duration in hypothesis
 - correct + missed detection + confusion = total speech duration  in reference

**Comment by chanansh** [comment]
Thanks. Can you please add this to the documentation or comment in the code? Thanks for contributing this package.

**Comment by hbredin** [comment]
I'd be happy to merge a pull request updating `DiarizationErrorRate`'s docstring.
